/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unindra.smartbrain.ui.reportCard;

import com.unindra.smartbrain.database.EntityManager;
import com.unindra.smartbrain.model.ReportCard;
import com.unindra.smartbrain.repository.ReportCardRepository;
import com.unindra.smartbrain.repository.IfaceReportCardRepository;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingUtilities;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author harunnurrasyid
 */
public class DashboardUI extends JFrame {

    private DefaultTableModel tableModel;

    /**
     * Creates new form ParticipantUI
     */
    public DashboardUI() {
        initComponents();
        initTableReportCard();
        
        // Center form
        this.setLocationRelativeTo(null);
    }
    
    public void initTableReportCard() {
        ReportCardPageButton.setEnabled(false);
        
        tableModel = new DefaultTableModel();
        tableModel.addColumn("ID");        
        tableModel.addColumn("Nama Pengajar");
        tableModel.addColumn("Nama Peserta");        
        tableModel.addColumn("Nama Kursus");        
        tableModel.addColumn("Nilai");
        tableModel.addColumn("Tahun Ajaran");
        
        EntityManager entityManager = new EntityManager();
        IfaceReportCardRepository repo = new ReportCardRepository(entityManager);
        List<ReportCard> reportCards = repo.getReportCards();
        
        for (ReportCard reportCard : reportCards) {
            tableModel.addRow(new Object[]{reportCard.getId(), reportCard.getInstructorName(), reportCard.getParticipantName(), reportCard.getCourseName(), reportCard.getScore(), reportCard.getSchoolYear()});
        }
        
        tableReportCard.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        itemUpdate = new javax.swing.JMenuItem();
        itemDetail = new javax.swing.JMenuItem();
        itemDelete = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReportCard = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        sideBarPanel = new javax.swing.JPanel();
        participantPageButton = new javax.swing.JButton();
        instructorPageButton = new javax.swing.JButton();
        ReportCardPageButton = new javax.swing.JButton();
        coursePageButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        itemUpdate.setText("Edit");
        itemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUpdateActionPerformed(evt);
            }
        });
        popupMenu.add(itemUpdate);

        itemDetail.setText("Detail");
        popupMenu.add(itemDetail);

        itemDelete.setText("Delete");
        itemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeleteActionPerformed(evt);
            }
        });
        popupMenu.add(itemDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableReportCard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Pengajar", "Nama Peserta", "Nama Kursus", "Nilai", "Tahun Ajaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableReportCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableReportCardMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableReportCard);

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-reset.png"))); // NOI18N
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                refreshButtonMousePressed(evt);
            }
        });

        participantPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-male_user.png"))); // NOI18N
        participantPageButton.setText("Peserta");
        participantPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                participantPageButtonMousePressed(evt);
            }
        });

        instructorPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-administrator_male.png"))); // NOI18N
        instructorPageButton.setText("Pengajar");
        instructorPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                instructorPageButtonMousePressed(evt);
            }
        });

        ReportCardPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-conference.png"))); // NOI18N
        ReportCardPageButton.setText("Raport");
        ReportCardPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReportCardPageButtonMousePressed(evt);
            }
        });

        coursePageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-literature.png"))); // NOI18N
        coursePageButton.setText("Kursus");
        coursePageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coursePageButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(instructorPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(participantPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coursePageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReportCardPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(instructorPageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(participantPageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coursePageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReportCardPageButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add.png"))); // NOI18N
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createButtonMousePressed(evt);
            }
        });

        printButton.setText("Print");
        printButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                printButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(printButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(refreshButton, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(createButton, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(printButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableReportCardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReportCardMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON3) {
            if (SwingUtilities.isRightMouseButton(evt) && tableReportCard.getSelectedRowCount() != 0) {
                popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tableReportCardMouseReleased

    private void itemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeleteActionPerformed
        int selectedRow = tableReportCard.getSelectedRow();
        
        if (selectedRow >= 0) {
            int id = (int) tableReportCard.getValueAt(selectedRow, 0);
            EntityManager entityManager = new EntityManager();
            IfaceReportCardRepository repo = new ReportCardRepository(entityManager);
            repo.deleteReportCardById(id);
            
            initTableReportCard();
        }
    }//GEN-LAST:event_itemDeleteActionPerformed

    private void refreshButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMousePressed
        initTableReportCard();
    }//GEN-LAST:event_refreshButtonMousePressed

    private void itemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUpdateActionPerformed
        int currentRow = tableReportCard.getSelectedRow();
        JFrame frame = new FormUpdateUI(
                tableReportCard.getValueAt(currentRow, 0).toString(),
                tableReportCard.getValueAt(currentRow, 1).toString(),
                tableReportCard.getValueAt(currentRow, 2).toString(),
                tableReportCard.getValueAt(currentRow, 3).toString(),
                tableReportCard.getValueAt(currentRow, 4).toString(),
                tableReportCard.getValueAt(currentRow, 5).toString()
        );
        
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // frame.getContentPane().add(mainPanel); // or whatever...
        frame.pack();
        frame.setLocationRelativeTo(null);  // *** this will center your app ***
        frame.setVisible(true);
    }//GEN-LAST:event_itemUpdateActionPerformed

    private void instructorPageButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instructorPageButtonMousePressed
        JFrame frame = new com.unindra.smartbrain.ui.instructor.DashboardUI();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // frame.getContentPane().add(mainPanel); // or whatever...
        frame.pack();
        frame.setLocationRelativeTo(null);  // *** this will center your app ***
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_instructorPageButtonMousePressed

    private void participantPageButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_participantPageButtonMousePressed
        JFrame frame = new com.unindra.smartbrain.ui.participant.DashboardUI();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // frame.getContentPane().add(mainPanel); // or whatever...
        frame.pack();
        frame.setLocationRelativeTo(null);  // *** this will center your app ***
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_participantPageButtonMousePressed

    private void coursePageButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursePageButtonMousePressed
        JFrame frame = new com.unindra.smartbrain.ui.course.DashboardUI();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // frame.getContentPane().add(mainPanel); // or whatever...
        frame.pack();
        frame.setLocationRelativeTo(null);  // *** this will center your app ***
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_coursePageButtonMousePressed

    private void ReportCardPageButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportCardPageButtonMousePressed
        initTableReportCard();
    }//GEN-LAST:event_ReportCardPageButtonMousePressed

    private void createButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMousePressed
        JFrame frame = new FormCreateUI();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // frame.getContentPane().add(mainPanel); // or whatever...
        frame.pack();
        frame.setLocationRelativeTo(null);  // *** this will center your app ***
        frame.setVisible(true);    }//GEN-LAST:event_createButtonMousePressed

    private void printButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printButtonMousePressed
        EntityManager entityManager = new EntityManager();
        IfaceReportCardRepository repo = new ReportCardRepository(entityManager);
        List<ReportCard> reportCards = repo.getReportCards();
        
        try {
            JasperReport report = JasperCompileManager.compileReport(getClass().getResourceAsStream("/reports/reportCard.jrxml"));
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(reportCards);
            
            JasperPrint jp = JasperFillManager.fillReport(report, new HashMap(), dataSource);
            
            JasperViewer.viewReport(jp); 
        } catch (JRException | java.lang.NoClassDefFoundError ex) {
            JOptionPane.showMessageDialog(null, "\nData Tidak Ditemukan\n" + ex, "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_printButtonMousePressed
                                               
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReportCardPageButton;
    private javax.swing.JButton coursePageButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton instructorPageButton;
    protected javax.swing.JMenuItem itemDelete;
    protected javax.swing.JMenuItem itemDetail;
    protected javax.swing.JMenuItem itemUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton participantPageButton;
    public javax.swing.JPopupMenu popupMenu;
    private javax.swing.JButton printButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JPanel sideBarPanel;
    public javax.swing.JTable tableReportCard;
    // End of variables declaration//GEN-END:variables
}
